### ISSUE TITLE
Upload improvement

### ISSUE THREAD

**Issue by fsforna** [softwareloop/uploader-plus#77] opened 2015-05-08 15:03 UTC
Dear All,
could you investigate the possibility to improve the project by adding a new feature that when the user upload files has the possibility to specify a type and metadata for the full set of uploaded files?

Thank you for your GREAT work. It should be part of Alfresco Share core.

Best Regards,
Francesco.

**Comment by mail2hemant** [comment] 2015-07-06 07:08
Yes, allowing multiple files to tag with single document type and metadata will be great advantage to the solution.

**Comment by douglascrp** [comment] 2015-07-21 15:38
It seems to be the same idea of the issue #62

**Comment by awster** [comment] 2016-08-31 08:51
Are there any plans for adding this (#62, #77) feature in the near future?
Thank you for your great work.

**Comment by douglascrp** [comment] 2016-12-27 13:41
@awster I guess there is no "plan".
The problem is that all the contributors are busy.
Could you try to implement it and share the result?

@softwareloop Can you close this one as this is a duplicate of #62 ?

**Comment by softwareloop** [comment] 2016-12-29 20:31
Duplicate of #62

**Closed by softwareloop** 2016-12-29 20:31 UTC
Labels: duplicate
