### ISSUE TITLE
uploading issue - operation failure popup.

### ISSUE THREAD

**Issue by monicakumari** [softwareloop/uploader-plus#122] opened 2017-08-22 06:56 UTC
[uploadexception.docx](https://github.com/softwareloop/uploader-plus/files/1241281/uploadexception.docx)

while using uploader plus, applying on document library(the root folder of a site) - it just through some exception and a popup on the sceen, says operation failure. -  multiple users reported the issue.
I have attached the exception details. 
as a developer, what I should do? or where should I look for the issue ?

**Comment by yregaieg** [comment] 2017-08-22 13:29
Sounds like you have a node  with a corrupt name, try replacing 
```ftl
"path": "${node.displayPath}\/${node.properties.name}",
```
with
```ftl
"path": "${node.displayPath!js_string}\/${node.properties.name!js_string}",
```
in `tomcat/webapps/alfresco/WEB-INF/classes/alfresco/templates/webscripts/com/softwareloop/uploader-plus/upload-folders-new.post.json.ftl`
then restart alfresco or refresh repo webscripts 
and let me know if that solves it ?

**Comment by monicakumari** [comment] 2017-08-23 06:35
I did the same.. but it did not worked.

I am attaching the error popup. and the exceptions.
[uploader-plus_exception.docx](https://github.com/softwareloop/uploader-plus/files/1244366/uploader-plus_exception.docx)
![screenshot from 2017-08-23 12-01-24](https://user-images.githubusercontent.com/26789477/29601873-4102e358-87fb-11e7-853c-368c9b1d5390.png)

**Comment by yregaieg** [comment] 2017-08-23 08:27
@monicakumari does admin user face the same issue ?

**Comment by monicakumari** [comment] 2017-08-23 08:28
yes, I am working as an admin.

**Comment by yregaieg** [comment] 2017-08-23 08:30
Alright, if you confirm that you can easily reproduce this as admin, can you also confirm that solr tracking is working ?

**Comment by monicakumari** [comment] 2017-08-23 08:30
yes.

**Comment by monicakumari** [comment] 2017-08-23 08:32
This error is only coming when we try to apply the uploader plus on the documentLibrary of the particular site.

**Comment by monicakumari** [comment] 2017-08-23 08:34
uploader plus is working fine for the individual folders. but issue comes when we are applying this to the documentLibrary folder of a particular website.

**Comment by yregaieg** [comment] 2017-08-23 08:56
Alright then! Is there a chance your site (or any of the folders inside document library) has a strange (or special) names ?

**Comment by monicakumari** [comment] 2017-08-23 09:02
I have applied an action on a folder using add-on.

**Comment by monicakumari** [comment] 2017-08-23 09:04
can you please help me to understand, what kind of strange or special names ??

**Comment by monicakumari** [comment] 2017-08-23 09:08
I have applied some rule on some folders.

**Comment by yregaieg** [comment] 2017-08-23 09:14
Can you share more details about the addon?

**Comment by yregaieg** [comment] 2017-08-23 09:17
Is there a chance it has behaviours that fiddle with file names / add some custom permission logic / add some custom versioning logic ?

**Comment by monicakumari** [comment] 2017-08-23 09:27
yes.. I have applied folder-quota action/add-on on some folder. applied some rules over some folders. other than this, all folders/data looks fine

**Comment by monicakumari** [comment] 2017-08-23 09:38
I have checked the documentLibrary folder using node browser too.. but there is no issue with this folder.

**Comment by yregaieg** [comment] 2017-08-23 09:45
OK,

I will give you this last hint, although I am not confident it would work !
Could you try and set this as the content of your `upload-folders-new.post.js`

```js
<import resource="classpath:/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/parse-args.lib.js">

var storeType = url.templateArgs.store_type;
var storeId = url.templateArgs.store_id;
var id = url.templateArgs.id;

var nodeRef = storeType + "://" + storeId + (id == null ? "" : ("/" + id));
var node = ParseArgs.resolveNode(nodeRef);
model.node = node;
logger.warn("Just fetched the node and nodeRef was set to :" + node.nodeRef); // new line

if (node.hasAspect("up:UploadFolder")) {
    model.status = 1;
    } else {
    var props = new Array(2);
    props["up:allowedTypes"] = null;
    node.addAspect("up:UploadFolder", props);
    node.save();
    logger.warn("Just saved the node and nodeRef was set to :" + node.nodeRef); // new line
    model.node = node; // new line
    model.status = 0;
    }
```

Restart alfresco/refresh repo webscripts and see if that solves it !

**Comment by monicakumari** [comment] 2017-08-23 09:46
okay, I am checking it.

**Comment by monicakumari** [comment] 2017-08-23 10:14
getting the same popup. 

exceptions.. 
[uploader-plus_exception.docx](https://github.com/softwareloop/uploader-plus/files/1245036/uploader-plus_exception.docx)

**Comment by yregaieg** [comment] 2017-08-23 16:36
I would be interested in checking the warn messages from the two lines in the log before the errors !

**Comment by monicakumari** [comment] 2017-08-24 07:57
sure, can you please tell me - what line should be added to show this warn message in log4j.properties file ?
because whatever the exception or messages came, I have already sent you.
thank you.

**Comment by monicakumari** [comment] 2017-08-24 11:29
I have tried curl command using noderef id. 

 **curl -uadmin:admin -X POST  http://localhost:8080/alfresco/service/uploader-plus/upload-folders-new/workspace/SpacesStore/8f2105b4-daaf-4874-9e8a-2152569d109b** 
got result-----

{
"status": 0,
"node": {
"nodeRef": "workspace://SpacesStore/9b38e1b6-7d8c-4504-bb97-97aac47e225d",
"path": "\/Company Home\/Sites\/testSite\/documentLibrary",
"allowedTypes": []
}
}
**this was correct and uploader plus was working fine for this node.**

another one--
**curl -uadmin:admin -X POST  http://localhost:8080/alfresco/service/uploader-plus/upload-folders-new/workspace/SpacesStore/00b4b77b-f57e-42ff-86dc-49302c2a34d0**

and the result ----

{
    "status" : 
  {
    "code" : 500,
    "name" : "Internal Error",
    "description" : "An error inside the HTTP server which prevented it from fulfilling the request."
  },  
  
  "message" : "07240089 Wrapped Exception (with status template): 07240021 Error during processing of the template 'get(properties) failed on instance of org.alfresco.repo.template.TemplateNode. See cause exception.\n\nThe failing instruction:\n==> ${node.properties.name!js_string} auto-escaped  [in template \"uploader-plus\/upload-folders-new.post.json.ftl\" at line 6, column 31]'. Please contact your system administrator.",  
  "exception" : "",
  
  "callstack" : 
  [ 
  	   
  ],
  
  "server" : "Community v5.2.0 (r135134-b14) schema 10,005",
  "time" : "Aug 24, 2017 4:26:20 PM"
}

**here the issue for this documentLibrary folder.**

**Comment by tusharkhanka** [comment] 2018-06-19 10:11
hi one of our customers got affected with the same kinda issue i checked in the node browser from admin console turns out the buggy folder that gets this "operation Failed issue" has an issue with "cm:tagScopeCache | d:content | null | " so couldn't exactly reproduce the steps. can you plase share if it can be a cause to the isse since on the logs it is same as @monicakumari  has shared

**Comment by deepaktalape** [comment] 2018-09-10 06:16
@monicakumari  You got any resolotion/work around for this issue, As I am also facing same issue, and not do anything. Thanks in Advance.

**Comment by monicakumari** [comment] 2018-09-11 09:07
please check tusharkhanka's resolution.

**Comment by deepaktalape** [comment] 2018-09-11 09:27
@monicakumari  Actually I am not clear with the comments provided by @tusharkhanka , It will be helpful if you share the cause of issue and resolution for this.  Thanks in Advance

**Closed** 2018-10-25 06:00 UTC

**Comment by douglascrp** [comment] 2019-06-16 22:24
I have just faced with the described issue the quick and dirty "fix" for it was to remove the cm:tagscope aspect from the documentLibrary on this "broken" site, using JavaScript console using the code below:
```
document.removeAspect("cm:tagscope");
```
I got the idea from the answer provided by @tusharkhanka
