### ISSUE TITLE
Uploader plus messes up with the initialization of some form controls

### ISSUE THREAD

**Issue by yregaieg** [softwareloop/uploader-plus#127] opened 2017-10-19 14:17 UTC
When you use some form control that need to be initialized as soon as it gets added to the dom (ie: the alfresco-value-assistance-addon); This process sometimes become tricky when you either have uploaded a document using uploader-plus before the last page refresh or when you are trying to upload multiple documents at the same time.

This problem only occurs when the formcontrol in question is part of the default (first in the list) form authorized in the current upload folder and the form in question happens to have been the last form to be used after the last page refresh.

If you have multiple upload forms available, you could switch to an other form and back and the issue is solved.

A workaround is to refresh the page and upload next document, but it is very painful.

**Comment by yregaieg** [comment] 2017-10-19 14:26
@douglascrp already fixed this issue but will need to clean up my implementation and test all edge cases before I make a PR

**Comment by douglascrp** [comment] 2017-10-20 17:28
Closing

**Comment by softwareloop** [comment] 2018-01-29 15:10
Hi, I have tested cf2c2dd7f1fee6552a2a7f6cfd5017a8ce94554b and I believe it breaks the "Apply the same metadata set to all files" functionality. To replicate the problem:

* set up an uploader-plus folder from the admin panel
* visit the folder
* upload two files, either using the upload button or by drag&drop
* click on "Apply the same metadata set to all files"
* enter any required fields
* click ok

The following problem is observed:

* the header of the upload popup stays on, see image below
* one has to click on the "X" button to make it go away
* the files are not uploaded

![uploader-plus-error](https://user-images.githubusercontent.com/6525590/35516958-6d233d86-050d-11e8-9608-75da55e94b2d.png)

I have tested on Alfresco versions 201704, 201701, 201604, 201602 always using Chrome. @yregaieg can you confirm you see the same?

The problem may be related to the code:

```
                while (formNode.hasChildNodes()) {
                    formNode.removeChild(formNode.lastChild);
                }
```

I'm re-opening this issue so we can discuss some changes.

**Comment by yregaieg** [comment] 2018-01-29 15:28
@softwareloop I confirm being able to reproduce this with the scenario described.
I will try to reserve some time during this week to re-test https://github.com/softwareloop/uploader-plus/pull/128#issuecomment-338285072 and see if @douglascrp  implementation is any better in this regard.

**Comment by softwareloop** [comment] 2018-01-29 15:40
I've tested @douglascrp 's https://github.com/douglascrp/uploader-plus/tree/issue-127-B branch and it is also affected.

I manually tested the most recent commits to be sure. The last commit that is NOT affected by the problem is 32e08420ea2b919024b2fd42f9e5c1c5b4d8e2bd

**Comment by yregaieg** [comment] 2018-01-29 16:19
I will have a deeper look at the code tonight and keep you posted.

**Comment by yregaieg** [comment] 2018-01-29 20:46
@softwareloop the reason behind this bug is that that we have removed all children from the form after the first iteration (ie: after building the first upload payload) and so the consequent files fail silently.
Not sure if the index of the item is available in the closure  or not, but if it is I think we should do one test more and only remove form children if the option for using the same metadataset for all documents is not active, or if it is active and we are at the very last iteration.

**Comment by softwareloop** [comment] 2018-01-30 14:10
I'm trying to reconstruct the data flow, also looking at https://github.com/softwareloop/uploader-plus/blob/master/docs/alfresco-uploader-plus-diagrams.pdf although the diagram is only partial.

Looking at dnd-upload-plus.js:

1. the entry point is _spawnUploads at dnd-upload-plus:46
2. if the folder is regular (not an uploader-plus folder), it will call _spawnUploads of the superclass
3. if it is an uploader-plus folder, it will call showMetadataDialog
4. in showMetadataDialog, if there are no more files to process, it will call  _spawnUploads of the superclass
5. if there is a file to process, if will fire the "change" event on the type selector
6. the event is picked up by uploader-plus-mixin:120, method onContentTypeChange
7. onContentTypeChange will do an ajax call to retrieve the form from share
8. when the form is received, onMetadataFormReceived is called
9. onMetadataFormReceived takes care of:
    * calling onReady to initialise the form
    * setting up the Next/ok button listener
    * resetting the "use same metadata" checkbox and listener
10. at this point the user is in control, fills in some data and clicks on next/ok
11. The next/ok button listener is onMetadataSubmit at uploader-plus-mixin:286
12. This will validate/process the metadata and, if selected, apply the same metadata to the remaining files (@douglascrp can you confirm?)
13. onMetadataSubmit finally call showMetadataDialog and the cycle is repeated from step 4

@yregaieg, do you see a place where the DOM/form cleanup can take place? Maybe in step 4 (showMetadataDialog) or step 12 (onMetadataSubmit).

Feel free to correct/improve my analysis of the data flow.

**Comment by yregaieg** [comment] 2018-01-30 15:47
As far as I can remember, I couldn't delay it to a later spot nor advance it to an earlier spot, and it needed to be run twice for some uploaders so that it would be supported on other uploaders as well (that last part, I am not sure if I was able to avoid it eventually ... as I had a client in my back urging me for a deployment)

We can definitely limit that cleanup to when we are not using the option for using the same metadata set for multiple uploads, either way, the bug it solves doesn't show up unti you try to fill in the form a second time... Or we could go further, and pass on the status along to the method for processing the upload (in case the information is not yet available in the closure) to only do the cleanup after processing the very last document to be uploaded when that option is on

**Comment by softwareloop** [comment] 2018-01-31 08:23
@yregaieg I have time this week to do some overall testing of the plugin and make an official release (v1.6). Is it ok if I revert cf2c2dd7f1fee6552a2a7f6cfd5017a8ce94554b and then re-apply it on a separate branch, so we can work on this issue in the next 1.7-SNAPSHOT?

**Comment by yregaieg** [comment] 2018-01-31 09:53
Perfectly fine by me

**Comment by softwareloop** [comment] 2018-01-31 10:17
Thanks

**Comment by softwareloop** [comment] 2018-02-01 09:49
I have released v1.6 as discussed. I have now pushed a new branch https://github.com/softwareloop/uploader-plus/tree/issue-127 and applied the previous commit 3365102b5aa1016f6e1ae5f3a4898abc6b21107f

**Comment by yregaieg** [comment] 2018-02-01 11:11
Thanks for the update!

**Comment by douglascrp** [comment] 2018-05-30 17:23
Hello guys.
I will have to look at this issue, as we are going to use uploader-plus in a new project we are working right now, and we are facing the problem described here.

Is there any chance that you have tried something to fix it? Or should I simply get the discarded commits and try to make it work?

**Comment by douglascrp** [comment] 2018-06-01 13:46
@softwareloop Ok, no problem.
I am going to work on this issue right now.

**Comment by douglascrp** [comment] 2018-06-01 21:02
Any chance that you guys can review and test this new version?
I was playing with it, trying to combine a lot of different steps, using both one-by-one and use same metadata, and judging by my tests, everything seems to be working well.

I am going to deploy this version in my development server and ask the users to test it too.

**Comment by douglascrp** [comment] 2018-06-03 16:54
It is not working... I am doing more tests.

**Comment by douglascrp** [comment] 2018-06-03 18:26
Ok guys, I have made one more change, and this time we were not able to make it fail.
Please, if you can, execute some tests before we merge this.

**Comment by yregaieg** [comment] 2018-06-11 09:56
@douglascrp I do not have access to a test environment anymore, but the code seems solid

**Comment by softwareloop** [comment] 2018-07-19 20:20
@douglascrp, @yregaieg, you've done a great job to resolve this tough issue. Thank you. @douglascrp 
 has helped me set up a test environment with alfresco-value-assistance, a custom content model and uploader-plus, so I could test compatibility from Alfresco 201602 to 201707. Everything worked great!

**Closed by softwareloop** 2018-07-19 20:20 UTC
